services:
  backend:
    image: php:8.2-fpm
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network
    environment:
      - APP_ENV=development

networks:
  app_network:
    driver: bridge
